[tool.black]
line-length = 120
target-version = ["py311"]
src = ["src"]

[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "F", "I", "UP"]

[tool.pytest.ini_options]
addopts = "-ra --cov=src"
testpaths = [
    "src/api/",
    "src/gunicorn_test.py"
]
pythonpath = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 100
