site_name: Azure AI Proxy

nav:
  - Introduction: index.md
  - Capacity Planning: capacity.md
  - Resources: resources.md
  - Events: events.md
  - Attendees: attendee.md
  - Reporting: reporting.md
  - Playground: playground.md
  - SDKs: sdk.md
  - Deployment: deployment.md
  - Workshops: workshops.md
  - FAQ: faq.md


plugins:
  - glightbox

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg
